# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Print Java version
      run: java -version
    
    - name: Setup gradle
      run: |
        sudo apt-get update
        sudo apt-get install -y gradle
    
    - name: Decomp Workspace
      run: gradle setupDecompWorkspace
    
    - name: Build
      run: gradle build

    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: build/libs
